services:
  backend:
    build:
      context: ./Backend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - PORT=3002
      - DB_HOST=db  # Connect to db container
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=customersdb
    volumes:
      - ./Backend:/src
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./Frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - ./Frontend:/src
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: customersdb
      MYSQL_INNODB_FAST_SHUTDOWN: "1"
      MYSQL_INITDB_SKIP_TZINFO: 1
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./DataBase:/docker-entrypoint-initdb.d  # Mount the Database folder containing your customersdb.sql
      - ./my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf  # Mount your custom config
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
